"""Secure storage for outbound share credentials.

Secrets live under ~/.config/ugraph/share/, never in the Obsidian vault.
Files are created with mode 0600 and refused if the mode is ever wider.
"""

from __future__ import annotations

import os
import stat
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover
    import tomli as tomllib  # type: ignore[no-redef]

from ugraph.share.draft import ShareError

X_KEYS = (
    "api_key",
    "api_secret",
    "access_token",
    "access_token_secret",
)

ENV_MAP = {
    "api_key": "UGRAPH_X_API_KEY",
    "api_secret": "UGRAPH_X_API_SECRET",
    "access_token": "UGRAPH_X_ACCESS_TOKEN",
    "access_token_secret": "UGRAPH_X_ACCESS_TOKEN_SECRET",
}


def config_home() -> Path:
    override = os.environ.get("UGRAPH_CONFIG_HOME")
    if override:
        return Path(override).expanduser().resolve()
    xdg = os.environ.get("XDG_CONFIG_HOME")
    if xdg:
        return Path(xdg).expanduser().resolve() / "ugraph"
    return Path.home() / ".config" / "ugraph"


def share_dir() -> Path:
    path = config_home() / "share"
    path.mkdir(parents=True, exist_ok=True)
    # Directory itself should not be group/world traversable for new installs.
    path.chmod(0o700)
    return path


def x_secrets_path() -> Path:
    return share_dir() / "x.toml"


def _assert_private(path: Path) -> None:
    mode = path.stat().st_mode
    if mode & (stat.S_IRWXG | stat.S_IRWXO):
        raise ShareError(
            f"refusing to read {path}: permissions are too open "
            f"(got {stat.filemode(mode)}; need 0600).\n"
            f"  Fix with:  chmod 600 {path}"
        )


def _write_private(path: Path, body: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    # Atomic replace: write temp then rename so a crash cannot leave a half-file
    # with the wrong mode.
    tmp = path.with_suffix(path.suffix + ".tmp")
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(body)
        os.replace(tmp, path)
    except Exception:
        try:
            tmp.unlink(missing_ok=True)
        except OSError:
            pass
        raise
    path.chmod(0o600)
    _assert_private(path)
    return path


def set_x_credentials(
    api_key: str,
    api_secret: str,
    access_token: str,
    access_token_secret: str,
) -> Path:
    """Persist OAuth 1.0a user-context credentials for X posting."""
    values = {
        "api_key": api_key.strip(),
        "api_secret": api_secret.strip(),
        "access_token": access_token.strip(),
        "access_token_secret": access_token_secret.strip(),
    }
    missing = [k for k, v in values.items() if not v]
    if missing:
        raise ShareError(f"missing credential fields: {', '.join(missing)}")

    # TOML with quoted strings; never interpolate user input into a template that
    # could break out of the string — escape backslash and quotes.
    def esc(value: str) -> str:
        return value.replace("\\", "\\\\").replace('"', '\\"')

    body = (
        "# ugraph share credentials for X.\n"
        "# Mode 0600. Never commit this file. Never paste it into a vault.\n"
        "# Generated by `ugraph x auth set`.\n\n"
        "[x]\n"
        + "\n".join(f'{key} = "{esc(values[key])}"' for key in X_KEYS)
        + "\n"
    )
    return _write_private(x_secrets_path(), body)


def get_x_credentials() -> dict[str, str]:
    """Resolve X credentials: environment wins, then the private secrets file."""
    from_env = {key: os.environ.get(env, "").strip() for key, env in ENV_MAP.items()}
    if all(from_env.values()):
        return from_env

    path = x_secrets_path()
    if not path.is_file():
        raise ShareError(
            "no X credentials configured.\n"
            "  Run:  ugraph x auth set\n"
            "  Or set UGRAPH_X_API_KEY / UGRAPH_X_API_SECRET / "
            "UGRAPH_X_ACCESS_TOKEN / UGRAPH_X_ACCESS_TOKEN_SECRET"
        )
    _assert_private(path)
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    section = data.get("x") or {}
    out = {}
    for key in X_KEYS:
        out[key] = (from_env.get(key) or str(section.get(key) or "")).strip()
    missing = [k for k, v in out.items() if not v]
    if missing:
        raise ShareError(f"X credentials incomplete — missing: {', '.join(missing)}")
    return out


def x_status() -> dict[str, str | bool | None]:
    """Redacted status suitable for printing. Never returns secret values."""
    path = x_secrets_path()
    file_ok = False
    mode = None
    if path.is_file():
        st = path.stat().st_mode
        mode = stat.filemode(st)
        file_ok = not bool(st & (stat.S_IRWXG | stat.S_IRWXO))
    env_set = [env for env in ENV_MAP.values() if os.environ.get(env)]
    configured = False
    try:
        get_x_credentials()
        configured = True
    except ShareError:
        configured = False
    return {
        "configured": configured,
        "secrets_file": str(path) if path.is_file() else None,
        "file_mode": mode,
        "file_private": file_ok if path.is_file() else None,
        "env_vars_set": env_set,
    }
