"""
indexes.py — Regenerate every index.md in the knowledge base.

Deterministic and idempotent: same KB contents in, byte-identical indexes out.
No LLM. This is the navigation layer agents traverse — it must never drift from
what is actually on disk.

Grouping comes from the taxonomy. Entries whose group is unrecognized land under
"Other" so nothing is ever silently dropped.

The byte-identical property is what makes `check()` usable as a CI gate: if a
rebuild would change any file, the indexes are stale and the working tree is
lying about what the KB contains.

    build_all(config)  -> [(path, content), ...]   pure; touches nothing
    write_all(config)  -> [path, ...]              writes; returns files changed
    check(config)      -> [path, ...]              writes nothing; returns stale files

Presentation (printing, exit codes) belongs to the CLI, not here.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from ugraph.config import Config
from ugraph.model import Page, iter_pages, relpath_between

GENERATED_NOTE = (
    "<!-- Generated by `ugraph index` — do not edit by hand. "
    "Edit the source pages' `description` field instead. -->"
)


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def _entry(index_path: Path, page: Page) -> str:
    """One index line: - [Title](rel/path.md) — description"""
    link = relpath_between(index_path, page.path)
    desc = page.description or "_no description_"
    return f"- [{page.title}]({link}) — {desc}"


def _render(index_path: Path, title: str, intro: str, groups: dict[str, list[Page]],
            group_order: list[str], frontmatter_desc: str) -> str:
    """Assemble a full index.md document."""
    lines = [
        "---",
        "type: overview",
        f'title: "{title}"',
        f'description: "{frontmatter_desc}"',
        "---",
        "",
        GENERATED_NOTE,
        "",
        f"# {title}",
        "",
        intro,
        "",
    ]

    total = sum(len(v) for v in groups.values())
    if total == 0:
        lines.append("_Nothing here yet._")
        lines.append("")
        return "\n".join(lines)

    ordered = [g for g in group_order if groups.get(g)]
    ordered += sorted(g for g in groups if g not in group_order and groups[g])

    for group in ordered:
        pages = sorted(groups[group], key=lambda p: p.title.lower())
        lines.append(f"## {group}")
        lines.append("")
        lines.extend(_entry(index_path, p) for p in pages)
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Per-directory builders
# ---------------------------------------------------------------------------

def build_concepts_index(config: Config, tax: dict) -> tuple[Path, str]:
    index_path = config.concepts / "index.md"
    labels = tax["domains"]
    order = [labels[d] for d in tax["domain_order"] if d in labels]

    groups = defaultdict(list)
    for page in iter_pages(config, root=config.concepts):
        if page.type != "concept":
            continue
        groups[labels.get(page.domain, "Other")].append(page)

    content = _render(
        index_path,
        "Concepts",
        "Ideas, techniques, and patterns — synthesized across every source that taught them. "
        "Grouped by domain. Follow a concept's typed relationship headings to traverse the graph.",
        groups,
        order,
        "Every concept page in the knowledge base, grouped by domain.",
    )
    return index_path, content


def build_entities_index(config: Config, tax: dict) -> list[tuple[Path, str]]:
    labels = tax["entity_subtypes"]
    results = []

    # One index per subtype directory.
    by_subtype = defaultdict(list)
    for page in iter_pages(config, root=config.entities):
        if page.type != "entity":
            continue
        by_subtype[str(page.meta.get("subtype", "")).strip()].append(page)

    domain_labels = tax["domains"]
    domain_order = [domain_labels[d] for d in tax["domain_order"] if d in domain_labels]

    # subtype -> directory name, taken from the taxonomy rather than derived.
    # Explicit because naive pluralization gives "persons".
    dirs = tax["entity_dirs"]
    for subtype, label in labels.items():
        if subtype not in dirs:
            raise KeyError(
                f"taxonomy `entity_dirs` has no directory for entity subtype {subtype!r}. "
                "Add it explicitly — it is not derived from the subtype name."
            )
        subdir = config.entities / dirs[subtype]
        index_path = subdir / "index.md"
        groups = defaultdict(list)
        for page in by_subtype.get(subtype, []):
            groups[domain_labels.get(page.domain, "Other")].append(page)
        results.append((index_path, _render(
            index_path,
            label,
            f"{label} referenced across the knowledge base, grouped by domain.",
            groups,
            domain_order,
            f"{label} referenced across the knowledge base.",
        )))

    # Roll-up index at entities/ itself.
    root_index = config.entities / "index.md"
    groups = defaultdict(list)
    for subtype, label in labels.items():
        for page in by_subtype.get(subtype, []):
            groups[label].append(page)
    results.append((root_index, _render(
        root_index,
        "Entities",
        "Tools, people, and organizations that appear in the knowledge base. "
        "An entity page says what the thing *is*; concept pages say what it's *for*.",
        groups,
        list(labels.values()),
        "All tools, people, and organizations in the knowledge base.",
    )))

    return results


def build_sources_index(config: Config, tax: dict) -> tuple[Path, str]:
    index_path = config.sources / "index.md"
    labels = tax["source_types"]

    groups = defaultdict(list)
    for page in iter_pages(config, root=config.sources):
        if page.type != "source":
            continue
        st = str(page.meta.get("source_type", "")).strip()
        channel = str(page.meta.get("channel", "")).strip()
        # Videos group by channel; everything else by source_type.
        if st == "video" and channel:
            groups[f"Videos — {channel}"].append(page)
        else:
            groups[labels.get(st, "Other")].append(page)

    content = _render(
        index_path,
        "Sources",
        "One page per consumed artifact — video, paper, article, thread. "
        "Each links to its immutable transcript in `raw/` and carries the timestamps "
        "concepts cite back to.",
        groups,
        [],  # alphabetical; channels are open-ended
        "Every source the knowledge base was built from.",
    )
    return index_path, content


def build_root_index(config: Config, tax: dict) -> tuple[Path, str]:
    """The KB entry point — what an agent reads first."""
    index_path = config.kb / "index.md"

    counts: defaultdict[str, int] = defaultdict(int)
    domains: defaultdict[str, int] = defaultdict(int)
    for page in iter_pages(config):
        counts[page.type] += 1
        if page.type == "concept" and page.domain:
            domains[page.domain] += 1

    labels = tax["domains"]
    domain_lines = [
        f"- **{labels.get(d, d)}** — {domains[d]} concept{'s' if domains[d] != 1 else ''}"
        for d in tax["domain_order"] if domains.get(d)
    ] or ["- _no concepts yet_"]

    moc_lines = []
    if config.mocs.is_dir():
        for page in iter_pages(config, root=config.mocs):
            # Only direct children of _mocs/ — subdirectories are working material.
            if page.path.parent != config.mocs:
                continue
            link = relpath_between(index_path, page.path)
            moc_lines.append(f"- [{page.title}]({link})")

    lines = [
        "---",
        "type: overview",
        'title: "Knowledge Base"',
        'description: "Entry point for this knowledge base — start here."',
        "---",
        "",
        GENERATED_NOTE,
        "",
        "# Knowledge Base",
        "",
        "> An LLM-navigable wiki. Plain markdown, YAML frontmatter, relative links.",
        "> No database, no embeddings. Start here and follow links — never load the whole folder.",
        "",
        "## How to use this",
        "",
        "1. Read [SCHEMA.md](SCHEMA.md) to understand page types and typed relationships.",
        "2. Scan the directory index that matches your question:",
        "   [Concepts](concepts/index.md) · [Entities](entities/index.md) · "
        "[Sources](sources/index.md)",
        "3. Open only the pages you need. Follow `## Prerequisites`, `## Builds on`,",
        "   `## Related` to traverse.",
        "4. Cite claims back to a source page and timestamp: `(source @ 00:14:32)`.",
        "5. If the answer isn't here, **say so** — do not fill the gap from general knowledge.",
        "",
        "## Contents",
        "",
        (f"- **{counts['concept']}** concepts · **{counts['entity']}** entities · "
         f"**{counts['source']}** sources"),
        "",
        "### By domain",
        "",
        *domain_lines,
        "",
    ]

    if moc_lines:
        lines += [
            "## Curated maps",
            "",
            "Hand-written narrative overviews. Opinionated where the generated "
            "indexes are neutral.",
            "",
            *moc_lines,
            "",
        ]

    lines += [
        "## Provenance",
        "",
        "Every claim traces to `sources/`, which traces to an immutable transcript in `raw/`.",
        "Transcripts are never edited — they are the audit trail.",
        "",
    ]

    return index_path, "\n".join(lines)


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def build_all(config: Config) -> list[tuple[Path, str]]:
    """Render every index for `config`'s knowledge base.

    Pure: reads the KB, touches nothing. Returns (path, content) pairs in a
    stable order so callers can diff, write, or check them.
    """
    tax = config.taxonomy()
    outputs = [build_concepts_index(config, tax)]
    outputs += build_entities_index(config, tax)
    outputs.append(build_sources_index(config, tax))
    outputs.append(build_root_index(config, tax))
    return outputs


def _stale(outputs: list[tuple[Path, str]]) -> list[tuple[Path, str]]:
    """The subset of `outputs` whose on-disk content differs from what we'd write."""
    changed = []
    for path, content in outputs:
        existing = path.read_text(encoding="utf-8") if path.is_file() else None
        if existing != content:
            changed.append((path, content))
    return changed


def write_all(config: Config) -> list[Path]:
    """Write every index that would change. Returns the paths actually written.

    Files whose content already matches are left untouched, so an up-to-date KB
    produces no mtime churn and no git diff.
    """
    written = []
    for path, content in _stale(build_all(config)):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def check(config: Config) -> list[Path]:
    """Return the indexes that are stale, writing nothing.

    An empty list means `write_all()` would be a no-op. That equivalence is the
    whole point — it is what lets CI fail on a stale index without a KB checkout
    diverging from the committed one.
    """
    return [path for path, _ in _stale(build_all(config))]
